sonar.projectKey=lnbitsbox
sonar.projectName=LNbitsBox
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=\
  **/.git/**,\
  **/node_modules/**,\
  **/dist/**,\
  **/build/**,\
  **/result/**,\
  **/result-*/**,\
  **/*.lock,\
  flake.lock
